// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseProjectRoot() {
  return window['go']['main']['App']['ChooseProjectRoot']();
}

export function GetProjectStatus() {
  return window['go']['main']['App']['GetProjectStatus']();
}

export function RunEvaluate(arg1) {
  return window['go']['main']['App']['RunEvaluate'](arg1);
}

export function RunIngest() {
  return window['go']['main']['App']['RunIngest']();
}

export function RunPipeline(arg1) {
  return window['go']['main']['App']['RunPipeline'](arg1);
}

export function TraceFigure(arg1, arg2) {
  return window['go']['main']['App']['TraceFigure'](arg1, arg2);
}

export function VerifyDeterminism(arg1) {
  return window['go']['main']['App']['VerifyDeterminism'](arg1);
}
