// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ChooseProjectRoot():Promise<main.ProjectStatus>;

export function GetProjectStatus():Promise<main.ProjectStatus>;

export function RunEvaluate(arg1:string):Promise<main.CommandResult>;

export function RunIngest():Promise<main.CommandResult>;

export function RunPipeline(arg1:string):Promise<main.PipelineResult>;

export function TraceFigure(arg1:string,arg2:string):Promise<main.CommandResult>;

export function VerifyDeterminism(arg1:string):Promise<main.CommandResult>;
